# Generated by Django 3.2.10 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tag',
            field=models.CharField(default='default_tag', max_length=255),
        ),
    ]
