# Generated by Django 3.2.18 on 2023-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231127_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tag',
            field=models.CharField(default='default_tag', max_length=500),
        ),
    ]
