# Generated by Django 3.2.18 on 2023-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_newsletter_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client_filter',
            field=models.CharField(max_length=1000),
        ),
    ]
