# Generated by Django 3.2.18 on 2023-11-27 14:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_newsletter_client_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client_filter',
            field=models.JSONField(default=dict),
        ),
    ]
