# Generated by Django 4.2.7 on 2023-11-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='newsletter',
            new_name='campaign',
        ),
    ]
